services:
  client:
    build: ./client
    ports:
      - "3000:80"  # Port 80 inside container exposed as 3000 outside
    depends_on:
      - server

  server:
    build: ./server
    expose:
      - "8080"
